### ISSUE TITLE
Blocking breaks website

### ISSUE THREAD

**Issue by Kees1958** [anarki999/Adblock-List-Archive#1]
Blocking fncstatic.com on foxnews.com 

Blocking fonts.googleapis.com on all sites using it

**Comment by anarki999** [comment]
Can you specific how fncstatic.com breaks foxnews.com?

It seems ok and working on my computer.

I will unlock fonts.googleapis.com that all sites using it =D

**Comment by Kees1958** [comment]
That is a late response :-) 

I thought foxnews.com

**Comment by anarki999** [comment]
Oh, I found that blocking "fncstatic.com" on foxnews.com will block the video from playing. I have unlocked "fncstatic.com". Please update my block list again =D
