### ISSUE TITLE
Steam is broken with new update to better

### ISSUE THREAD

**Issue by leetfin** [anarki999/Adblock-List-Archive#4]
Filter||edgesuite.net^$3p
Filter listBetter.fyi Trackers Blocklist 
Contextsteamcommunity.com
Partyness(3) steamcommunity.com ⇒ edgesuite.net
Typeimage
URLhttps://steamcommunity-a.akamaihd.net.edgesuite.net/
CNAMEsteamcommunity-a.akamaihd.net ⇒
 steamcommunity-a.akamaihd.net.edgesuite.net
Original URLhttps://steamcommunity-a.akamaihd.net/public/shared/images/responsive/header_menu_hamburger.png

**Comment by anarki999** [comment]
ok, I will delete "edgesuite.net^3p" filter =D
