### ISSUE TITLE
Issue with ||akamai.net^$third-party

### ISSUE THREAD

**Issue by alxthaman** [anarki999/Adblock-List-Archive#5]
Hello!

||akamai.net^$third-party breaks the Humble Bundle store.

https://www.humblebundle.com/store

**Comment by anarki999** [comment]
> Hello!
> 
> ||akamai.net^$third-party breaks the Humble Bundle store.
> 
> https://www.humblebundle.com/store

Okay, I locked up the "||akamai.net^$third-party" the filter. Please update my list again and try again if my list breaks the website again =D
