### ISSUE TITLE
Possibility to create a host file?

### ISSUE THREAD

**Issue by gallegonovato** [anarki999/Adblock-List-Archive#6]
Good afternoon:

First of all thank you for your hard work, effort, your time and for your lists.

I would like to ask you a question if I may. 

I don't know if it would be possible to create a host file, to be able to use your work also with Adaway?

If you would be so kind to take my consideration and if you can do it, I would be grateful.

Receive a warm embrace and thank you for your time.

**Comment by anarki999** [comment]
Yo bro, you are welcome. A very late response. It's impossible for me to make it to be a host file. Host file only contains ip address of all those address. But mine one are focusing on anti-adblocking and anti-tracking by any "adblock detector" script. It focuses on the div elements which will be able to detect your adblocker.

I would recommend few host files for you by the btw and will list it in the homepage of this Github page too =)

At list they are working in my Android AdGuard DNS filtering:

https://adaway.org/hosts.txt
https://filters.adtidy.org/android/filters/15_optimized.txt
https://blocklistproject.github.io/Lists/tracking.txt
https://raw.githubusercontent.com/bongochong/CombinedPrivacyBlockLists/master/NoFormatting/hosts.final
https://someonewhocares.org/hosts/zero/hosts
https://ewpratten.retrylife.ca/youtube_ad_blocklist/hosts.ipv4.txt
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
